name: Test Envoi Email Gmail

# Déclenchement manuel via l'interface GitHub
on:
  workflow_dispatch:

jobs:
  send_email:
    runs-on: ubuntu-latest
    env:
      GOOGLE_CLIENT_ID: ${{ secrets.GOOGLE_CLIENT_ID }}
      GOOGLE_CLIENT_SECRET: ${{ secrets.GOOGLE_CLIENT_SECRET }}
      GOOGLE_REFRESH_TOKEN: ${{ secrets.GOOGLE_REFRESH_TOKEN }}
      GOOGLE_SENDER_EMAIL: ${{ secrets.GOOGLE_SENDER_EMAIL }}
      TO_EMAIL: ${{ secrets.TO_EMAIL }} # destinataire du test
    steps:
      - name: Checkout du dépôt
        uses: actions/checkout@v3

      - name: Installer Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Installer les dépendances
       
      - name: Envoyer le mail test
        run: node send-mail.js

